# NumPy

- This is a numeric processing Library that is faster than Python and is used to perform statistical task with the CSV file data. NumPy is build upon Python and uses API. 
- Numpy looks a lot like list with the difference being that it is more faster and powerful.

##### Pandas is build upon NumPy and uses numpy to perform the statistical calculation part. 



In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [4]:
# Acessing a particular element
a[1]

2

In [5]:
# Slicing from a particular part to the end
a[2:]

array([3, 4, 5, 6])

In [6]:
# Slicing
a[1:3]

array([2, 3])

In [8]:
# Step Slicing: Output every element at 2nd position from the current
a[::2]


array([1, 3, 5])

In [9]:
# Multi-Indexing 
# SPECIAL IN NUMPY

a[[0,-1,3]]

array([1, 6, 4])

In [10]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8]
]
)

In [11]:
A.shape

(2, 4)

In [12]:
# Dimensions of the Numpy
A.ndim

2

In [13]:
A.size

8

In [17]:
B = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [9,10,11,12],
        [13,14,15,16]
    ]
])

B

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [16]:
print(B.size)
print(B.shape)
print(B.ndim)

16
(2, 2, 4)
3


#### Indexing and Slicing

In [18]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8]
]
)

In [19]:
A[1]

array([5, 6, 7, 8])

In [20]:
A[1][3]

8

In [22]:
A[1,3]

8

In [23]:
A[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# A[Rows to select, Columns to select]
A[0:2, 0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [30]:
# Axis=0 is column wise
# axis=1 is row wise
print(A.sum(axis=0))
print(A.sum(axis=1))

[ 6  8 10 12]
[10 26]


In [31]:
print(A.std(axis=0))
print(A.mean(axis=0))
print(A.var(axis=0))

[2. 2. 2. 2.]
[3. 4. 5. 6.]
[4. 4. 4. 4.]


In [32]:
print(A.std(axis=1))
print(A.mean(axis=1))
print(A.var(axis=1))

[1.11803399 1.11803399]
[2.5 6.5]
[1.25 1.25]


### Broadcasting and Vectorizing Operations

- It broadcasts the calculation to every element in the array. All this operation is fast as fuck.

In [34]:
C = np.arange(7)
C

array([0, 1, 2, 3, 4, 5, 6])

In [36]:
print(C + 10)
print(C - 4)
print()

[10 11 12 13 14 15 16]
[-4 -3 -2 -1  0  1  2]


In [37]:
# Boolean Array
C >= 4

array([False, False, False, False,  True,  True,  True])

In [38]:
# Filtering the Array according to familiar Syntax
C[C>=4]

array([4, 5, 6])

In [40]:
C.mean()

3.0

In [42]:
C[C<C.mean()]

array([0, 1, 2])

In [46]:
# Random Module

D = np.random.randint(100, size=(5,3))
D

array([[ 0, 89, 61],
       [ 5, 29, 70],
       [ 2, 59, 70],
       [16, 94, 62],
       [27, 79, 34]])

In [50]:
A = np.random.randint(100, size=(3,3))
B = np.random.randint(30, size=(3,3))

print(A)
print(B)

[[99 97 19]
 [33  1 36]
 [97 25 54]]
[[22 28  8]
 [10  4 26]
 [28 22 13]]


In [51]:
A.dot(B)

array([[3680, 3578, 3561],
       [1744, 1720,  758],
       [3896, 4004, 2128]])

In [52]:
A @ B

array([[3680, 3578, 3561],
       [1744, 1720,  758],
       [3896, 4004, 2128]])

In [53]:
B.T

array([[22, 10, 28],
       [28,  4, 22],
       [ 8, 26, 13]])

In [54]:
B.T @ A

array([[5224, 2844, 2290],
       [5038, 3270, 1864],
       [2911, 1127, 1790]])

#### Random

In [58]:
print(np.random.random(size=2))
print(np.random.normal(size=2))
print(np.random.rand(2, 4))

[0.90219829 0.6845481 ]
[-2.03604437  0.45077661]
[[0.03990402 0.42640012 0.12068566 0.23673941]
 [0.58656429 0.06853132 0.42510532 0.86969316]]


#### Arrange

In [59]:
print(np.arange(10))
print(np.arange(5, 10))
print(np.arange(0, 1, .1))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### Reshape

In [60]:
print(np.arange(10).reshape(2, 5))
print(np.arange(10).reshape(5, 2))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### LinSpace

In [61]:
print(np.linspace(0, 1, 5))
print(np.linspace(0, 1, 20))
print(np.linspace(0, 1, 20, False))

[0.   0.25 0.5  0.75 1.  ]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


#### Zeros, Ones, Empty

In [63]:
print(np.zeros(5))
print(np.zeros((3, 3)))
print(np.zeros((3, 3), dtype=np.int64))
print(np.ones(5))
print(np.ones((3, 3)))
print(np.empty(5))
print(np.empty((2, 2)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]
[[0.25 0.5 ]
 [0.75 1.  ]]


#### Identity and Eye

In [64]:
print(np.identity(3))
print(np.eye(3, 3))
print(np.eye(8, 4))
print(np.eye(8, 4, k=1))
print(np.eye(8, 4, k=-3))
print("Hello World"[6])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
W
